var nowUnit;
var nowChapter;
$('.content').hide();
$('.chapterIndex').hide();
$('.subject').hide();
$('body').show();
function createSpan(unit) {
	return "<p style='text-decoration:none;color: black;font-size: 28px;'>" + unit + "</p>";
}
function createUnit(unit) {
	return "<a href='javascript:unit(\"" + unit + "\");' class='" + unit + " unitIndex' style='text-decoration:none;color: black;font-size: 24px;'>&nbsp;" + unit + "</a>";
}
function createChapter(chapter,unit) {
	return "<a href='javascript:chapter(\"" + chapter + "\",\"" + unit +"\");' class='biology chapterIndex u" + unit + " c" + chapter + "' style='text-decoration:none;color: black;font-size: 20px;'> &nbsp;&nbsp;&nbsp;" + chapter + "</a>";
}
function subject(subject) {
	$('.chapterIndex').hide();
	$('.content').hide();
	$('.subject').hide();
	if (subject == '#society') {
		$('#geography'   ).show();
		$('#history'     ).show();
		$('#citizen'     ).show();
	} else if (subject == '#natural'){
		$('#biology'     ).show();
		$('#science'     ).show();
		$('#earthScience').show();
	} else {
		$(subject).show();
	}
}
function unit(unit) {
	$('.chapterIndex').hide();
	$('.u' + unit).show();
	nowUnit = unit;
}
function chapter(chapter, unit) {
	$('#' + nowChapter).hide();
	$('.c' + nowChapter).css("font-weight","normal");
	$('.u' + unit).show();
	$('.c' + chapter).css("font-weight","bold");
	$('#' + chapter).show();
	nowChapter = chapter;
}
//---數學目錄---
$("#math"      ).append(createUnit("整數的運算"));
$("#math"      ).append(createChapter("數與數線","整數的運算"));
$("#math"      ).append(createChapter("整數的加減運算","整數的運算"));
$("#math"      ).append(createChapter("整數的乘除運算","整數的運算"));
$("#math"      ).append(createChapter("指數律","整數的運算"));
$("#math"      ).append(createChapter("科學記號","整數的運算"));
$("#math"      ).append(createUnit("分數的運算"));
$("#math"      ).append(createChapter("因數與倍數","分數的運算"));
$("#math"      ).append(createChapter("最大公因數與最小公倍數","分數的運算"));
$("#math"      ).append(createChapter("分數的加減運算","分數的運算"));
$("#math"      ).append(createChapter("分數的乘除與四則運算","分數運算"));
$("#math"      ).append(createUnit("一元一次方程式"));
$("#math"      ).append(createChapter("以符號列式與運算","一元一次方程式"));
$("#math"      ).append(createChapter("一元一次方程式的列式與求解","一元一次方程式"));
$("#math"      ).append(createChapter("一元一次方程式的應用","一元一次方程式"));
$("#math"      ).append(createUnit("二元一次聯立方程式"));
$("#math"      ).append(createChapter("二元一次方程式","二元一次聯立方程式"));
$("#math"      ).append(createChapter("二元一次聯立方程式","二元一次聯立方程式"));
$("#math"      ).append(createChapter("應用問題","二元一次聯立方程式"));
$("#math"      ).append(createUnit("二元一次方程式的圖形"));
$("#math"      ).append(createChapter("直角坐標平面","二元一次方程式的圖形"));
$("#math"      ).append(createChapter("二元一次方程式的圖形","二元一次方程式的圖形"));
$("#math"      ).append(createChapter("求直線方程式及二元一次","二元一次方程式的圖形"));
$("#math"      ).append(createChapter("聯立方程式的圖形","二元一次方程式的圖形"));
$("#math"      ).append(createUnit("比例與線型函數"));
$("#math"      ).append(createChapter("比例式","比例與線型函數"));
$("#math"      ).append(createChapter("連比例","比例與線型函數"));
$("#math"      ).append(createChapter("正比與反比","比例與線型函數"));
$("#math"      ).append(createChapter("函數","比例與線型函數"));
$("#math"      ).append(createChapter("線型函數及其圖形","比例與線型函數"));
$("#math"      ).append(createUnit("一次不等式"));
$("#math"      ).append(createChapter("一次不等式","一次不等式"));
$("#math"      ).append(createChapter("解一元一次不等式","一次不等式"));
$("#math"      ).append(createChapter("應用問題","一次不等式"));
$("#math"      ).append(createUnit("乘法公式與多項式"));
$("#math"      ).append(createChapter("乘法公式","乘法公式與多項式"));
$("#math"      ).append(createChapter("乘法公式的應用","乘法公式與多項式"));
$("#math"      ).append(createChapter("多項式的加減","乘法公式與多項式"));
$("#math"      ).append(createChapter("多項式的乘除","乘法公式與多項式"));
$("#math"      ).append(createUnit("平方根與畢氏定理"));
$("#math"      ).append(createChapter("平方根與近似值","平方根與畢氏定理"));
$("#math"      ).append(createChapter("根式的化簡與四則運算","平方根與畢氏定理"));
$("#math"      ).append(createChapter("畢氏定理","平方根與畢氏定理"));
$("#math"      ).append(createUnit("因式分解"));
$("#math"      ).append(createChapter("因式分解","因式分解"));
$("#math"      ).append(createChapter("十字交乘法","因式分解"));
$("#math"      ).append(createUnit("一元二次方程式"));
$("#math"      ).append(createChapter("一元二次方程式","一元二次方程式"));
$("#math"      ).append(createChapter("配方法與公式解","一元二次方程式"));
$("#math"      ).append(createChapter("應用問題","一元二次方程式"));
$("#math"      ).append(createUnit("等差數列與等差級數"));
$("#math"      ).append(createChapter("等差數列","等差數列與等差級數"));
$("#math"      ).append(createChapter("等差級數","等差數列與等差級數"));
$("#math"      ).append(createUnit("幾何圖形與尺規作圖"));
$("#math"      ).append(createUnit("三角形的基本性質"));
$("#math"      ).append(createUnit("平行與四邊形"));
$("#math"      ).append(createUnit("相似形"));
$("#math"      ).append(createUnit("圓形"));
$("#math"      ).append(createUnit("幾何證明與三角形的心"));
$("#math"      ).append(createUnit("二次函數"));
$("#math"      ).append(createUnit("立體圖形"));
$("#math"      ).append(createUnit("資料整理與統計"));
//---地理目錄---
$("#geography" ).append(createSpan("地理"));
$("#geography" ).append(createUnit("台灣地理"));
$("#geography" ).append(createChapter("地理位置與範圍","台灣地理"));
$("#geography" ).append(createChapter("地形","台灣地理"));
$("#geography" ).append(createChapter("海岸與島嶼","台灣地理"));
$("#geography" ).append(createChapter("天氣與氣候","台灣地理"));
$("#geography" ).append(createChapter("水文","台灣地理"));
$("#geography" ).append(createChapter("台灣的環境問題與環境保護","台灣地理"));
$("#geography" ).append(createChapter("人口","台灣地理"));
$("#geography" ).append(createChapter("第一級產業","台灣地理"));
$("#geography" ).append(createChapter("第二、三級產業","台灣地理"));
$("#geography" ).append(createChapter("聚落與交通","台灣地理"));
$("#geography" ).append(createChapter("台灣的區域特色及發展","台灣地理"));
$("#geography" ).append(createUnit("中國地理"));
$("#geography" ).append(createChapter("疆域與區域劃分","中國地理"));
$("#geography" ).append(createChapter("地形","中國地理"));
$("#geography" ).append(createChapter("氣候與水文","中國地理"));
$("#geography" ).append(createChapter("人口分布與人口問題","中國地理"));
$("#geography" ).append(createChapter("產業與經濟","中國地理"));
$("#geography" ).append(createChapter("資源問題與環境保育","中國地理"));
$("#geography" ).append(createChapter("南部地區","中國地理"));
$("#geography" ).append(createChapter("北部地區","中國地理"));
$("#geography" ).append(createChapter("西部地區","中國地理"));
$("#geography" ).append(createUnit("世界地理"));
$("#geography" ).append(createChapter("世界概說","世界地理"));
$("#geography" ).append(createChapter("東北亞","世界地理"));
$("#geography" ).append(createChapter("東南亞與南亞","世界地理"));
//---歷史目錄---
$("#history"   ).append(createSpan("歷史"));
$("#history"   ).append(createUnit("台灣歷史"));
$("#history"   ).append(createChapter("史前台灣與原住民文化","台灣歷史"));
$("#history"   ).append(createChapter("國際競爭下的台灣","台灣歷史"));
$("#history"   ).append(createChapter("鄭氏時期的經營","台灣歷史"));
$("#history"   ).append(createChapter("清領前期的政治與經濟","台灣歷史"));
$("#history"   ).append(createChapter("清領前期的社會與文化","台灣歷史"));
$("#history"   ).append(createChapter("清領後期的開港與建省","台灣歷史"));
$("#history"   ).append(createChapter("日治時期的殖民統治","台灣歷史"));
$("#history"   ).append(createChapter("日治時期的經濟發展","台灣歷史"));
$("#history"   ).append(createChapter("日治時期的社會與文化","台灣歷史"));
$("#history"   ).append(createChapter("戰後台灣的政治變遷","台灣歷史"));
$("#history"   ).append(createChapter("戰後台灣的外交與兩岸關係","台灣歷史"));
$("#history"   ).append(createChapter("戰後台灣的經濟與社會","台灣歷史"));
$("#history"   ).append(createUnit("中國歷史"));
$("#history"   ).append(createChapter("從史前到春秋戰國","中國歷史"));
$("#history"   ).append(createChapter("秦漢大一統帝國的建立","中國歷史"));
$("#history"   ).append(createChapter("魏晉南北朝的分與合","中國歷史"));
$("#history"   ).append(createChapter("胡漢融合的隋唐帝國","中國歷史"));
$("#history"   ).append(createChapter("多民族並立的宋元時期","中國歷史"));
$("#history"   ).append(createChapter("明代與盛清的發展","中國歷史"));
$("#history"   ).append(createChapter("晚清的變局","中國歷史"));
$("#history"   ).append(createChapter("清末的改革","中國歷史"));
$("#history"   ).append(createChapter("清朝的覆亡","中國歷史"));
$("#history"   ).append(createChapter("民初的政局與社會變遷","中國歷史"));
$("#history"   ).append(createChapter("國民政府的統治","中國歷史"));
$("#history"   ).append(createChapter("中華人民共和國的建立與發展","中國歷史"));
//---公民目錄---
$("#citizen"   ).append(createSpan("公民"));
$("#citizen"   ).append(createUnit("個人與社會生活"));
$("#citizen"   ).append(createChapter("自我的成長","個人與社會生活"));
$("#citizen"   ).append(createChapter("和諧的性別關係","個人與社會生活"));
$("#citizen"   ).append(createChapter("家庭生活","個人與社會生活"));
$("#citizen"   ).append(createChapter("家庭協奏曲","個人與社會生活"));
$("#citizen"   ).append(createChapter("友善校園與終身學習","個人與社會生活"));
$("#citizen"   ).append(createChapter("社區生活","個人與社會生活"));
$("#citizen"   ).append(createChapter("社會互動","個人與社會生活"));
$("#citizen"   ).append(createChapter("社會中的團體","個人與社會生活"));
$("#citizen"   ).append(createChapter("社會規範","個人與社會生活"));
$("#citizen"   ).append(createChapter("社會中的文化","個人與社會生活"));
$("#citizen"   ).append(createChapter("變遷中的社會","個人與社會生活"));
$("#citizen"   ).append(createChapter("社會福利","個人與社會生活"));
$("#citizen"   ).append(createUnit("民主的政治"));
$("#citizen"   ).append(createChapter("現代國家與民主政治","民主的政治"));
$("#citizen"   ).append(createChapter("中央政府","民主的政治"));
$("#citizen"   ).append(createChapter("地方政府","民主的政治"));
$("#citizen"   ).append(createChapter("政府的經濟功能","民主的政治"));
$("#citizen"   ).append(createChapter("政黨與利益團體","民主的政治"));
$("#citizen"   ).append(createChapter("政治參與和選舉","民主的政治"));
$("#citizen"   ).append(createUnit("法律生活"));
$("#citizen"   ).append(createChapter("法律的基本概念","法律生活"));
$("#citizen"   ).append(createChapter("人民的權利與義務","法律生活"));
$("#citizen"   ).append(createChapter("民法與生活","法律生活"));
$("#citizen"   ).append(createChapter("刑法與行政法規","法律生活"));
$("#citizen"   ).append(createChapter("權利救濟","法律生活"));
$("#citizen"   ).append(createChapter("少年的法律常識","法律生活"));
//---生物目錄---
$("#biology"   ).append(createSpan("生物"));
$("#biology"   ).append(createUnit("生命世界"));
$("#biology"   ).append(createChapter("生物與環境","生命世界"));
$("#biology"   ).append(createChapter("生物體的構造","生命世界"));
$("#biology"   ).append(createChapter("實驗&nbsp;顯微鏡的使用與科學方法","生命世界"));
$("#biology"   ).append(createChapter("物質進出細胞","生命世界"));
$("#biology"   ).append(createChapter("構成個體的層次","生命世界"));
$("#biology"   ).append(createUnit("養分的獲得"));
$("#biology"   ).append(createChapter("能量和酵素","養分的獲得"));
$("#biology"   ).append(createChapter("實驗&nbsp;養分的測定與酵素的分解作用","養分的獲得"));
$("#biology"   ).append(createChapter("植物怎樣製造養分","養分的獲得"));
$("#biology"   ).append(createChapter("實驗&nbsp;光合作用產物的檢測","養分的獲得"));
$("#biology"   ).append(createChapter("動物怎樣製造養分","養分的獲得"));
$("#biology"   ).append(createUnit("生物體內物質的運輸"));
$("#biology"   ).append(createChapter("植物體內物質的運輸","生物體內物質的運輸"));
$("#biology"   ).append(createChapter("實驗&nbsp;植物體內水分的運輸","生物體內物質的運輸"));
$("#biology"   ).append(createChapter("動物體內物質的運輸","生物體內物質的運輸"));
$("#biology"   ).append(createChapter("實驗&nbsp;探測心音與脈搏","生物體內物質的運輸"));
$("#biology"   ).append(createChapter("實驗&nbsp;血液流動的觀察","生物體內物質的運輸"));
$("#biology"   ).append(createUnit("協調作用"));
$("#biology"   ).append(createChapter("神經系統","協調作用"));
$("#biology"   ).append(createChapter("實驗&nbsp;與協調作用相關的實驗","協調作用"));
$("#biology"   ).append(createChapter("內分泌系統","協調作用"));
$("#biology"   ).append(createChapter("動物行為","協調作用"));
$("#biology"   ).append(createChapter("植物的感應","協調作用"));
$("#biology"   ).append(createUnit("恆定性"));
$("#biology"   ).append(createChapter("呼吸及氣體的恆定","恆定性"));
$("#biology"   ).append(createChapter("實驗&nbsp;生物的呼吸作用","恆定性"));
$("#biology"   ).append(createChapter("體溫的恆定","恆定性"));
$("#biology"   ).append(createChapter("血糖的恆定","恆定性"));
$("#biology"   ).append(createChapter("排泄作用與水分的恆定","恆定性"));
$("#biology"   ).append(createUnit("生殖"));
$("#biology"   ).append(createChapter("染色體、細胞分裂與減數分裂","生殖"));
$("#biology"   ).append(createChapter("無性生殖","生殖"));
$("#biology"   ).append(createChapter("有性生殖","生殖"));
$("#biology"   ).append(createChapter("實驗&nbsp;蛋的觀察","生殖"));
$("#biology"   ).append(createChapter("生殖行為","生殖"));
$("#biology"   ).append(createUnit("遺傳"));
$("#biology"   ).append(createChapter("遺傳法則","遺傳"));
$("#biology"   ).append(createChapter("基因與遺傳","遺傳"));
$("#biology"   ).append(createChapter("人類的遺傳","遺傳"));
$("#biology"   ).append(createChapter("突變與生物技術","遺傳"));
$("#biology"   ).append(createUnit("演化"));
$("#biology"   ).append(createChapter("演化的發生","演化"));
$("#biology"   ).append(createChapter("演化的證據","演化"));
$("#biology"   ).append(createChapter("生物的演化","演化"));
$("#biology"   ).append(createUnit("生物圈的生物"));
$("#biology"   ).append(createChapter("生物的命名與分類","生物圈的生物"));
$("#biology"   ).append(createChapter("原核生物界、原生生物界與菌物界","生物圈的生物"));
$("#biology"   ).append(createChapter("植物界","生物圈的生物"));
$("#biology"   ).append(createChapter("動物界","生物圈的生物"));
$("#biology"   ).append(createUnit("生物與環境"));
$("#biology"   ).append(createChapter("生態學的研究範疇","生物與環境"));
$("#biology"   ).append(createChapter("能量流動與物質循環","生物與環境"));
$("#biology"   ).append(createChapter("生態系的種類","生物與環境"));
$("#biology"   ).append(createChapter("人類與環境","生物與環境"));